const cartTypes = {
    TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
    ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
    REDUCE_ITEM_FROM_CART: "REDUCE_ITEM_FROM_CART",
    REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART"
};

export default cartTypes;
